export const FETCH_USERS_BEGIN   = 'FETCH_USERS_BEGIN';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';
export const FETCH_CHOSEN_ONE_BEGIN = 'FETCH_CHOSEN_ONE_BEGIN';
export const FETCH_CHOSEN_ONE_SUCCESS = 'FETCH_CHOSEN_ONE_SUCCESS';
export const FETCH_CHOSEN_ONE_FAILURE = 'FETCH_CHOSEN_ONE_FAILURE';

export const baseUrl = 'https://jsonplaceholder.typicode.com/users';